### ISSUE TITLE
store everything in JSON

### ISSUE THREAD

**Issue by JayDonigian** [JayDonigian/2016RoadTrip#25]
## Store Entire Journal in JSON File

Everything should be stored in the json file. If you delete an entry, it should be perfectly recreated when the script is run.

### Sub-Tasks

- [ ] https://github.com/JayDonigian/2016-road-trip/issues/42
- [ ] https://github.com/JayDonigian/2016-road-trip/issues/48
- [ ] https://github.com/JayDonigian/2016-road-trip/issues/49
